pipeline {
    agent any
    triggers {
        pollSCM '* * * * *'
    }
	
    stages {
		stage('checkout') {
            steps {
                checkout scm
            }
        }
	
		stage('Build App')
          {
            steps
             {
		     sh """ 
		     cd $WORKSPACE/swishh-frontend/
			 npm cache clean --force
			 npm install
		     ls -ltr
		     """
            }
          }
		  stage('Test')
          {
            steps
             {
		     sh """ 
		     cd $WORKSPACE/swishh-frontend/
			 npm cache clean --force
			 npm install
			 npm install --save-dev @testing-library/react
			 npm test
		     ls -ltr
		     """
            }
          }
		stage('Dockerising'){
			steps{
				//sh 'docker login -u swishhspring2021 -p Spring@2021'
				sh """ 
				cd $WORKSPACE/swishh-frontend/
				docker build -t swishhspring2021/swishhfrontend:latest .
				"""
				
			}
		}
		stage('Artifact Upload'){
			steps{
				sh 'docker login -u swishhspring2021 -p Spring@2021'
				sh 'docker push swishhspring2021/swishhfrontend:latest'
			}
		}
    }
}
