apiVersion: apps/v1
kind: Deployment
metadata:
  name: __APP_NAME__-deploy
  labels:
    app: __APP_NAME__
spec:
  replicas: __REPLICA__
  selector:
    matchLabels:
      app: __APP_NAME__
  template:
    metadata:
      labels:
        app: __APP_NAME__
        updateTimestamp: "__TIMESTAMP__"
    spec:
      containers:
      - name: __APP_NAME__
        image: __IMAGE__
        imagePullPolicy: Always
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
        resources:
          requests:
            cpu: 300m
          limits:
            cpu: 600m
            memory: 4Gi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: __APP_NAME__
  name: __APP_NAME__-service
spec:
  selector:
    app: __APP_NAME__
  ports:
    - protocol: TCP
      name: "3306"
      port: 3306
      targetPort: 3306
  type: __SERVICE_TYPE__
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: __APP_NAME__
  name: __APP_NAME__-ingress
spec:
  backend:
    serviceName: __APP_NAME__-service
    servicePort: 3306
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: __APP_NAME__
  name: __APP_NAME__-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: __APP_NAME__-deploy
  minReplicas: __REPLICA__
  maxReplicas: __MAX_REPLICA__
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 60