pipeline {
    agent any
    triggers {
        pollSCM '* * * * *'
    }
	
    stages {
		stage('Build App')
          {
            steps
             {
             sh "env"
              git branch: 'feature/jenkins', url: 'https://github.com/airavata-courses/Swishh.git'
		     sh """ 
		     cd $WORKSPACE/ImageStorage/
		     ls -ltr
		     """
              sh "mvn -f ImageStorage/pom.xml install -DskipTests=true"
            }
          }
        stage('Build') {
            steps {
                sh 'mvn -f ImageStorage/pom.xml clean install'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn -f ImageStorage/pom.xml install'
            }
        }
		stage('Dockerising'){
			steps{
				script{
					dockerImage = docker.build("swishhspring2021/imagestorage", "ImageStorage")
				}
				
			}
		}
		stage('Dockerhub'){
			steps{
				sh 'docker push swishhspring2021/imagestorage:latest'
			}
		}
    }
}
