pipeline {
    agent any
    triggers {
        pollSCM '* * * * *'
    }
	
    stages {
		stage('Build App')
          {
            steps
             {
             sh "env"
              git branch: 'feature/jenkins', url: 'https://github.com/airavata-courses/Swishh.git'
		     sh """ 
		     cd $WORKSPACE/ImageStorage/
		     ls -ltr
		     """
		     script {
                  def pom = readMavenPom file: 'ImageStorage/pom.xml'
                  version = pom.version
              }
              sh "mvn -f ImageStorage/pom.xml install -DskipTests=true"
            }
          }
        stage('Build') {
            steps {
                sh 'mvn -f ImageStorage/pom.xml clean install'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn -f ImageStorage/pom.xml install'
            }
        }
		stage('Dockerising'){
			steps{
				sh 'docker login -u swishhspring2021 -p Spring@2021'
				sh """ 
				cd $WORKSPACE/ImageStorage/
				ls -ltr
				sudo service docker start
				docker build -t swishhspring2021/imagestorage:latest .
				"""
				
			}
		}
		stage('Dockerhub'){
			steps{
				sh 'docker push swishhspring2021/imagestorage:latest'
			}
		}
    }
}
