pipeline {
    agent any
    triggers {
        pollSCM '* * * * *'
    }
    stages {
        stage('Build') {
            steps {
				echo dir
                bat 'mvn clean install'
            }
        }
        stage('Test') {
            steps {
				echo dir
                bat 'mvn install'
            }
        }
    }
}