version: 2.1
  
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    machine:true
    working_directory: ~/repo
    steps:
      - checkout
      - run: cd ImageStorage && ls -la && mvn dependency:go-offline&&mvn clean package
      - run: cd ImageStorage && ls -la && docker build .

      # store raw contents of src code
      - store_artifacts:
          path: /target/classes
          destination: swishh-imagestorage-api
