version: 2.1
  
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    steps:
      - checkout

      - run: ./imagestorage/mvn dependency:go-offline

      # package into a jar
      - run: ./imagestorage/mvn clean package

      # build and push docker image to docker hub
      - run: ./imagestorage/mvn clean compile jib:build -Dimage=swishh/imagestorage:$CIRCLE_BUILD_NUM

      # store raw contents of src code
      - store_artifacts:
          path: target/classes
          destination: swishh-imagestorage-springboot-api