version: 2.1
  
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    steps:
      - setup_remote_docker:
          version: 19.03.13
      - checkout
      - run: pwd
      - run: cd ImageStorage && ls -la && mvn dependency:go-offline&&mvn clean package && docker build . -f /home/circleci/repo/ImageStorage/Dockerfile

      # store raw contents of src code
      - store_artifacts:
          path: /target/classes
          destination: swishh-imagestorage-api
