version: 2.1
  
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    steps:
      - setup_remote_docker:
          version: 18.09.3
      - checkout
      - run: pwd
      - run: docker login --username $DOCKER_USER --password $DCOKER_PASS
      - run: cd ImageStorage && mvn clean install package && docker image build . -t swishhspring2021/image-storage:latest && docker push swishhspring2021/image-storage:latest
      - run: cd SessionManagement && mvn clean install package && docker image build . -t swishhspring2021/session-service:latest && docker push swishhspring2021/session-service:latest
      - run: cd swishh-frontend && docker image build . -t swishhspring2021/swsihh-ui:latest && docker push swishhspring2021/swishh-ui:latest
      
      - run: cd user-service && docker image build . -t swishhspring2021/user-service:latest && docker push swishhspring2021/user-service:latest
      
      - run: cd "Image Image Metadata" &&docker image build . -t swishhspring2021/metedata-service:latest && docker push swishhspring2021/metadata-service:latest

      # store raw contents of src code
      - store_artifacts:
          path: /target/classes
          destination: swishh-imagestorage-api

