pipeline {
    agent any
    triggers {
        pollSCM '* * * * *'
    }
	
    stages {
		stage('checkout') {
            steps {
                checkout scm
            }
        }
	
		stage('Build App')
          {
            steps
             {
		     sh """ 
		     cd $WORKSPACE/user-service/
			 virtualenv venv
			 . venv/bin/activate 
			 pip install -r requirements.txt
		     ls -ltr
		     """
            }
          }
		stage('Dockerising'){
			steps{
				//sh 'docker login -u swishhspring2021 -p Spring@2021'
				sh """ 
				cd $WORKSPACE/user-service/
				docker build -t swishhspring2021/userservice:latest .
				"""
				
			}
		}
		stage('Artifact Upload'){
			steps{
				sh 'docker login -u swishhspring2021 -p Spring@2021'
				sh 'docker push swishhspring2021/userservice:latest'
			}
		}
    }
}
