pipeline {
    agent any
    triggers {
        pollSCM '* * * * *'
    }
	
    stages {
		stage('checkout') {
            steps {
                checkout scm
            }
        }
	
		stage('Build App')
          {
            steps
             {
		     sh """ 
		     cd $WORKSPACE/SessionManagement/
		     ls -ltr
		     """
              sh "mvn -f SessionManagement/pom.xml install -DskipTests=true"
            }
          }
        
        stage('Test') {
            steps {
                sh 'mvn -f SessionManagement/pom.xml install'
            }
        }
		stage('Dockerising'){
			steps{
				sh """ 
				cd $WORKSPACE/SessionManagement/
				docker build -t swishhspring2021/sessionmanagement:latest .
				"""
				
			}
		}
		stage('Artifact Upload'){
			steps{
				sh 'docker login -u swishhspring2021 -p Spring@2021'
				sh 'docker push swishhspring2021/sessionmanagement:latest'
			}
		}
    }
}
